package com.sk.workitem.app.repository;

import java.util.List;

import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import com.sk.workitem.app.model.MasterOtp;

@Repository
public interface MasterOtpRepository extends CrudRepository<MasterOtp, Integer>{
	
	/***
	 * security code which are not expired are returned
	 * @param otpExpStatus {@link Boolean} Security code status
	 * @param userEmail {@link String} email of the user
	 * @return {@link List} {@link MasterOtp} with security code expired status as false
	 */
	public List<MasterOtp> findAllByOtpExpiredAndUserEmail(boolean otpExpStatus, String userEmail);
	
	/***
	 * find the {@link MasterOtp} record by using otpId
	 * @param otpId {@link Integer} otpid
	 * @return {@link MasterOtp} object matching otpId
	 */
	public MasterOtp findFirstByOtpId(int otpId);
	
	/***
	 * find a {@link MasterOtp} record by email and otpId
	 * @param email {@link String} email of the user 
	 * @param otpId {@link Integer} last generated otp id
	 * @return {@link MasterOtp} if found or else null
	 */
	@Query(value = "SELECT * FROM mstr_otp WHERE user_email = ?1 AND otp_id = ?2", nativeQuery = true)
	MasterOtp findByUserEmailAndOtpIdNative(String userEmail, int otpId);
	
	/***
	 * security code which are not expired are returned
	 * @param email {@link String} email of the user 
	 * @param otpExpStatus {@link Boolean} Security code status
	 * @param otpGenFor {@link String} otp generator for which purpose
	 * @param otpId {@link Integer} otpId generated by user
	 * @return {@link MasterOtp} with security code expired status as false
	 */
	public MasterOtp findByUserEmailAndOtpExpiredAndOtpGenForAndOtpId(String email, boolean otpExpStatus, String otpGenFor, Integer otpId);
	
	/***
	 * security code which are not expired are returned
	 * @param email {@link String} email of the user 
	 * @param otpExpStatus {@link Boolean} Security code status
	 * @param otpGenFor {@link String} otp generator for which purpose
	 * @param otpId {@link Integer} otpId generated by user
	 * @return {@link MasterOtp} with security code expired status as false
	 */
	public MasterOtp findByUserEmailAndOtpExpiredAndOtpGenFor(String email, boolean otpExpStatus, String otpGenFor);
	
	
	/***
	 * security code which are not expired are returned
	 * @param email {@link String} email of the user 
	 * @param otpExpStatus {@link Boolean} Security code status
	 * @param otpGenFor {@link String} otp generator for which purpose
	 * @return {@link MasterOtp} with security code expired status as false
	 */
	public MasterOtp findFirstByUserEmailAndOtpExpiredAndOtpGenFor(String email, boolean otpExpStatus, String otpGenFor, Sort sort);
	
}
