package com.sk.workitem.app.service;

import java.io.IOException;
import java.util.List;

import org.springframework.stereotype.Service;

import com.sk.workitem.app.model.MasterOtp;
import com.sk.workitem.app.repository.MasterOtpRepository;

import jakarta.mail.MessagingException;

@Service
public interface SecurityCodeService {
	
	/***
	 * 
	 * @param securityCode {@link String} security code generated for user
	 * @param codeReqFor {@link String} code requested for which function like login, 
	 * registration, reset, forgot_password
	 * @param userEmail {@link String} email of the user who requested otp
	 * @return {@link Boolean} true if security code is stored in db or else false 
	 */
	public boolean persistSecurityCode(String securityCode, String codeReqFor, String userEmail);
	
	/***
	 * Expires otp of the given MasterOtp object 
	 * @param mstrOtpObj {@link MasterOtp} object to expire the otp
	 * @param otpRepo {@link MasterOtpRepository}
	 * @return true if otp_expired is set to true in database or else false
	 */
	public boolean expireOtp(MasterOtp mstrOtpObj, MasterOtpRepository otpRepo);
	
	/***
	 * 
	 * @param securityCode {@link String} security code generated for user
	 * @param codeReqFor {@link String} code requested for which function like login, 
	 * registration, reset, forgot_password
	 * @param userEmail {@link String} email of the user who requested otp
	 * @param otpId {@link String} otp_id to expire 
	 * @return {@link Boolean} true if security code is stored in db or else false 
	 */
	public boolean persistSecurityCodeExpireOld(String securityCode, String codeReqFor, String userEmail, String otpId);
	
	/***
	 * send security code via email
	 * @param email {@link String} email of the user
	 * @param securityCode {@link String} security code generated
	 * @throws MessagingException 
	 * @throws IOException 
	 */
	public void sendSecurityCodeViaEmailLogin(String email, String securityCode, String codeReqFor) throws MessagingException, IOException;
	
	/***
	 * send security code via email
	 * @param email {@link String} email of the user
	 * @param securityCode {@link String} security code generated
	 * @throws MessagingException 
	 * @throws IOException 
	 */
	public void sendSecurityCodeViaEmailReset(String email, String securityCode, String codeReqFor) throws MessagingException, IOException;
	
	/***
	 * 
	 * @param mstrOtp {@link List<MasterOtp>} list of MasterOtp where all otp expired are false  
	 * @param otpRepo MasterOtpRepository 
	 * @return true if all otp are expired or else false 
	 */
	public boolean expireAllOtp(List<MasterOtp> mstrOtp, MasterOtpRepository otpRepo);
	
	/***
	 * validates whether the user entered code is valid or not
	 * @param codeReqFor {@link String} Security Code requested purpose
	 * @param securityCode {@link String}
	 * @param userEmail {@link String} email of the user
	 * @param otpId {@link String} old otpId generated by the user
	 * @return {@link String} true if its a valid code or else issue specific error message will be returned
	 */
	public String verifySecurityCode(String codeReqFor, String securityCode, String userEmail, String otpId);
	
	/***
	 * checks whether the previous otp is expired or not
	 * @param email {@link String} email of the logged in user
	 * @return true if the otp is expired or else false
	 */
	public boolean checkWhetherPreviousOtpExpired(String email);
	
	/***
	 * checks whether the previous reset otp is expired or not
	 * @param optId {@link String} userEmail
	 * @return true if the reset otp is expired or else false
	 */
	public boolean checkWhetherPreviousOtpExpiredReset(String userEmail);
	
	/***
	 * validates whether the user entered code is valid or not
	 * @param codeReqFor {@link String} Security Code requested purpose
	 * @param securityCode {@link String}
	 * @param userEmail {@link String} email of the user
	 * @param otpId {@link String} opt_id generated by the user
	 * @return {@link String} true if its a valid code or else issue specific error message will be returned
	 */
	public String verifySecurityCodeResetPwd(String codeReqFor, String securityCode, String userEmail, String otpId);
	
}
